import { ArrowRight, Check, ChevronDown, Code2, Database, Layers3, Menu, Network, Quote, ShieldCheck, Target, X } from 'lucide-react'
import { useState } from 'react'

const services=[
  {icon:Code2,title:'Sistemas web sob medida',text:'Operações, portais e plataformas que eliminam gargalos e centralizam processos.'},
  {icon:Layers3,title:'Produtos SaaS',text:'Da validação do MVP à arquitetura multi-tenant pronta para crescer.'},
  {icon:Network,title:'Integrações e APIs',text:'Conectamos ERPs, pagamentos, dados e serviços com segurança.'},
  {icon:Database,title:'Modernização de legados',text:'Evolução gradual de sistemas críticos, sem paralisar a operação.'},
]
const steps=[['01','Diagnóstico','Entendemos contexto, metas e restrições.'],['02','Estratégia','Definimos escopo, arquitetura e indicadores.'],['03','Design & Build','Prototipamos e entregamos em ciclos curtos.'],['04','Evolução','Medimos, aprendemos e escalamos o produto.']]
const faqs=[
 ['Vocês trabalham com empresas de qualquer segmento?','Sim. Nosso processo começa pelo entendimento do negócio e adapta tecnologia, arquitetura e linguagem ao contexto de cada cliente.'],
 ['A NtecSoftware também cria MVPs?','Sim. Estruturamos uma primeira versão enxuta para validar hipóteses, aprender rápido e evoluir com segurança.'],
 ['Como funcionam orçamento e prazo?','Após um diagnóstico inicial, apresentamos escopo, etapas, investimento e uma previsão realista de entrega.'],
 ['Vocês assumem sistemas já existentes?','Sim. Avaliamos código, infraestrutura e riscos para propor modernização, integração ou evolução gradual.'],
]

function Logo(){return <a href="#inicio" className="flex items-center gap-3 font-bold text-xl"><span className="grid size-10 place-items-center rounded-xl bg-gradient-to-br from-emerald-400 to-indigo-500 text-slate-950">N</span>ntecsoftware</a>}
function Button({children,secondary=false}:{children:React.ReactNode,secondary?:boolean}){return <a href="#contato" className={secondary?'btn btn-secondary':'btn btn-primary'}>{children}</a>}
function Heading({eyebrow,title,copy}:{eyebrow:string,title:string,copy:string}){return <div className="section-heading"><span>{eyebrow}</span><h2>{title}</h2><p>{copy}</p></div>}

export function App(){
 const [open,setOpen]=useState(false)
 const [faq,setFaq]=useState(0)
 return <div className="min-h-screen overflow-hidden bg-[#07101f] text-slate-50">
  <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#07101f]/85 backdrop-blur-xl">
   <div className="container flex h-20 items-center justify-between"><Logo/><nav className="hidden items-center gap-8 text-sm font-semibold text-slate-300 md:flex"><a href="#servicos">Serviços</a><a href="#processo">Processo</a><a href="#projetos">Projetos</a><a href="#sobre">Sobre</a><Button>Fale com um especialista</Button></nav><button className="md:hidden" aria-label="Abrir menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>
   {open&&<nav className="container grid gap-4 border-t border-white/10 py-5 text-slate-200 md:hidden"><a href="#servicos">Serviços</a><a href="#processo">Processo</a><a href="#projetos">Projetos</a><a href="#sobre">Sobre</a></nav>}
  </header>
  <main>
   <section id="inicio" className="hero-section"><div className="container grid items-center gap-14 lg:grid-cols-[1.05fr_.95fr]">
    <div><div className="eyebrow">● Software sob medida, sem limites</div><h1>Transformamos desafios complexos em software que impulsiona negócios.</h1><p className="hero-copy">Projetamos e desenvolvemos plataformas digitais, sistemas web, integrações e produtos SaaS sob medida — da estratégia à evolução contínua.</p><div className="mt-9 flex flex-wrap gap-3"><Button>Solicitar diagnóstico gratuito <ArrowRight size={17}/></Button><Button secondary>Conhecer projetos</Button></div><div className="mt-7 flex flex-wrap gap-x-6 gap-y-2 text-xs font-semibold text-slate-400">{['Arquitetura escalável','Entregas incrementais','Suporte próximo'].map(x=><span className="flex items-center gap-2" key={x}><Check size={14} className="text-emerald-400"/>{x}</span>)}</div></div>
    <div className="code-window"><div className="mb-5 flex gap-2"><i/><i/><i/></div><div className="code-block"><p><b>01</b> // seu desafio</p><p><b>02</b> const ideia = entender(negócio);</p><p><b>03</b> const produto = projetar(ideia);</p><p><b>04</b> const impacto = entregar(produto);</p><p className="text-emerald-400"><b>05</b> return escalar(impacto);</p></div><div className="mt-4 grid grid-cols-3 gap-2">{[['+ performance','Arquitetura'],['− retrabalho','Processo'],['↑ conversão','Experiência']].map(([a,b])=><div className="metric" key={a}><strong>{a}</strong><small>{b}</small></div>)}</div></div>
   </div></section>
   <section className="proof"><div className="container flex flex-col items-start justify-between gap-8 lg:flex-row lg:items-center"><p>Parceiros para construir o próximo estágio do seu negócio.</p><div className="grid w-full grid-cols-3 gap-6 lg:w-auto lg:gap-14">{[['+30','soluções'],['98%','satisfação'],['100%','sob medida']].map(([a,b])=><div key={a}><strong>{a}</strong><small>{b}</small></div>)}</div></div></section>
   <section id="servicos" className="section"><div className="container"><Heading eyebrow="O que construímos" title="Tecnologia desenhada para a realidade do seu negócio." copy="Não vendemos pacotes engessados. Combinamos estratégia, UX e engenharia para resolver o problema certo."/><div className="card-grid">{services.map(({icon:Icon,title,text},i)=><article className="service-card" key={title}><span>0{i+1}</span><Icon/><h3>{title}</h3><p>{text}</p><a href="#contato">Explorar solução <ArrowRight size={15}/></a></article>)}</div></div></section>
   <section id="processo" className="section bg-white/[.025]"><div className="container"><Heading eyebrow="Como trabalhamos" title="Clareza em cada etapa. Evolução em cada entrega." copy="Um processo colaborativo e previsível para reduzir risco e acelerar aprendizado."/><div className="steps">{steps.map(([n,t,p])=><article key={n}><strong>{n}</strong><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>
   <section id="projetos" className="section"><div className="container"><Heading eyebrow="Projetos" title="Soluções que conectam tecnologia a resultado." copy="Experiências digitais projetadas para operações reais e crescimento sustentável."/><div className="grid gap-5 lg:grid-cols-2">{[['HEALTHTECH','Plataforma inteligente de saúde','Dados, documentos e jornadas de cuidado.'],['ERP & OPERAÇÕES','Gestão integrada de ponta a ponta','Processos, indicadores e automações em um só lugar.']].map((c,i)=><article className="case-card" key={c[0]}><div className="mock"><span/><span/><span/></div><small>{c[0]}</small><h3>{c[1]}</h3><p>{c[2]}</p><a href="#contato">Ver estudo de caso <ArrowRight size={15}/></a></article>)}</div></div></section>
   <section id="sobre" className="section bg-white/[.025]"><div className="container"><Heading eyebrow="Por que a NtecSoftware" title="Engenharia forte. Comunicação simples. Visão de produto." copy="O parceiro técnico que entende o negócio antes de escrever a primeira linha de código."/><div className="grid gap-4 md:grid-cols-3">{[[Target,'Pensamento de produto','Decisões guiadas por impacto, não por volume de funcionalidades.'],[ShieldCheck,'Arquitetura preparada','Segurança, observabilidade e escala desde as fundações.'],[Network,'Transparência real','Você acompanha prioridades, progresso e riscos sem caixa-preta.']].map(([Icon,t,p])=><article className="feature-card" key={String(t)}><Icon className="text-emerald-400"/><h3>{String(t)}</h3><p>{String(p)}</p></article>)}</div></div></section>
   <section className="section"><div className="container"><Heading eyebrow="Confiança" title="Parcerias construídas para durar." copy="Tecnologia funciona melhor quando existe proximidade, responsabilidade e visão compartilhada."/><blockquote><Quote/><p>“A equipe transformou um processo confuso em uma solução clara, confiável e pronta para crescer com a operação.”</p><cite>Cliente parceiro • Transformação digital</cite></blockquote></div></section>
   <section className="section"><div className="container max-w-4xl"><Heading eyebrow="Perguntas frequentes" title="Antes de começar, vale saber." copy="Respostas diretas para as dúvidas mais comuns."/><div className="grid gap-3">{faqs.map(([q,a],i)=><button className="faq" key={q} onClick={()=>setFaq(faq===i?-1:i)} aria-expanded={faq===i}><span>{q}<ChevronDown className={faq===i?'rotate-180':''}/></span>{faq===i&&<p>{a}</p>}</button>)}</div></div></section>
   <section id="contato" className="cta"><div className="container text-center"><h2>Sua ideia merece uma solução à altura.</h2><p>Conte o desafio. Nós ajudamos a transformar em estratégia, produto e resultado.</p><a className="btn bg-slate-950 text-white hover:bg-slate-800" href="mailto:contato@ntecsoftware.com.br">Agendar conversa estratégica <ArrowRight size={17}/></a></div></section>
  </main>
  <footer><div className="container"><div className="footer-grid"><div><Logo/><p className="mt-5 max-w-sm text-sm leading-6 text-slate-400">Software sob medida para negócios que querem ir além.</p></div><div><b>Empresa</b><a href="#sobre">Sobre</a><a href="#processo">Processo</a><a href="#projetos">Projetos</a></div><div><b>Soluções</b><a href="#servicos">Sistemas web</a><a href="#servicos">SaaS</a><a href="#servicos">Integrações</a></div><div><b>Contato</b><a href="mailto:contato@ntecsoftware.com.br">contato@ntecsoftware.com.br</a><span>Atendimento online • Brasil</span><span>Seg–Sex • 08h às 18h</span></div></div><div className="footer-bottom"><span>© 2026 NtecSoftware. Todos os direitos reservados.</span><div><a href="#">Privacidade</a><a href="#">Termos</a></div></div></div></footer>
 </div>
}
